<template><div><h1 id="fetchpriority" tabindex="-1"><a class="header-anchor" href="#fetchpriority"><span>fetchpriority</span></a></h1>
<p>浏览器下载各种类型资源有一个默认的优先级，<a href="https://github.com/WICG/priority-hints/blob/main/EXPLAINER.md" target="_blank" rel="noopener noreferrer">priority-hints<ExternalLinkIcon/></a> 可以影响这个优先级。具体来说，是使用 <code v-pre>fetchpriority</code> 属性。</p>
<p><code v-pre>fetchpriority</code> 属性可以在 <code v-pre>link</code>、<code v-pre>img</code>、<code v-pre>script</code> 标签中使用，它有三种可选值：</p>
<ul>
<li>high：相对默认优先级高</li>
<li>low：相对默认优先级更低</li>
<li>auto：默认值，相当于没有设置</li>
</ul>
<div class="language-html" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>photo.png<span class="token punctuation">"</span></span> <span class="token attr-name">fetchprioroty</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>high<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
</code></pre></div><p>注意，<strong>fetchpriority 只是一种提示而非要求，浏览器可以根据实际情况处理资源的优先级</strong>。</p>
<h2 id="图片" tabindex="-1"><a class="header-anchor" href="#图片"><span>图片</span></a></h2>
<p>通常来说，浏览器会按照文档中出现的顺序加载图像，当发现图片在视口中，则会提高优先级。</p>
<p>fetchpriority 可以给浏览器一个提示，以便更快获取重要的图像。</p>
<div class="language-html" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>logo.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>product.jpg<span class="token punctuation">"</span></span> <span class="token attr-name">fetchpriority</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>high<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>carousel.jpg<span class="token punctuation">"</span></span> <span class="token attr-name">fetchpriority</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>low<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre></div><h2 id="async-脚本" tabindex="-1"><a class="header-anchor" href="#async-脚本"><span>async 脚本</span></a></h2>
<p>浏览器对 blocking script、async script 和 preload script 有不同的优先级。</p>
<p>如果浏览器默认 preload script 为高优先级，async script 为低优先级，那么 preload 一个 async 脚本的依赖会有问题。</p>
<p>假如我们有两个脚本 A 和 B，A 导入 B，预加载 B 就可以在加载 A 的同时开始获取。</p>
<div class="language-html" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A.js<span class="token punctuation">"</span></span> <span class="token attr-name">async</span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>preload<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>B.js<span class="token punctuation">"</span></span> <span class="token attr-name">as</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>script<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre></div><p>但这可能会导致 B 先于 A 被加载，因为 preload 优先级高于 async。</p>
<p>通过 priority hints 为两个脚本分配相同的优先级，它们就可以按顺序加载。</p>
<div class="language-html" data-ext="html" data-title="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A.js<span class="token punctuation">"</span></span> <span class="token attr-name">async</span> <span class="token attr-name">fetchpriority</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>high<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>preload<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>B.js<span class="token punctuation">"</span></span> <span class="token attr-name">as</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>script<span class="token punctuation">"</span></span> <span class="token attr-name">fetchpriority</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>high<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre></div><h2 id="fetch-api" tabindex="-1"><a class="header-anchor" href="#fetch-api"><span>fetch API</span></a></h2>
<p>fetch API 也可以提供优先级提示。</p>
<div class="language-javascript" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token function">fetch</span><span class="token punctuation">(</span><span class="token string">'/api/prefetch.json'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">priority</span><span class="token operator">:</span> <span class="token string">'low'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token comment">/*...*/</span><span class="token punctuation">)</span>
</code></pre></div></div></template>


